//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace курсовая_работа.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELIVERY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DELIVERY()
        {
            this.GOODS_ARIVAL = new HashSet<GOODS_ARIVAL>();
            this.GOODS_CARE = new HashSet<GOODS_CARE>();
        }
    
        public int DELIVERY_ID { get; set; }
        public int COUNTS { get; set; }
        public string NAMES { get; set; }
        public decimal PRICE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GOODS_ARIVAL> GOODS_ARIVAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GOODS_CARE> GOODS_CARE { get; set; }
    }
}
