//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace курсовая_работа.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public int EMPLOYEES_ID { get; set; }
        public int STOCK_ID { get; set; }
        public int ROLS_ID { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string MIDLENAME { get; set; }
        public string PHONE { get; set; }
        public string LOGINS { get; set; }
        public string PASSWORDS { get; set; }
    
        public virtual ROL ROL { get; set; }
        public virtual STOCK STOCK { get; set; }
    }
}
