//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace курсовая_работа.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INVOICE()
        {
            this.GOODS_ARIVAL = new HashSet<GOODS_ARIVAL>();
        }
    
        public int INVOICE_ID { get; set; }
        public decimal FINAL_SUM { get; set; }
        public int STOCK_ID { get; set; }
        public int PROVIDER_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GOODS_ARIVAL> GOODS_ARIVAL { get; set; }
        public virtual PROVIDER PROVIDER { get; set; }
        public virtual STOCK STOCK { get; set; }
    }
}
